SELECT SUBJ.SUBJ_NAME
  || ','
  || OBJ_NAME
  || ','
  || OBJ_TYPE OBJ,
  CASE LABELLED_LATEST
    WHEN 1
    THEN 'LATEST'
    ELSE 'NOT_LATEST'
  END
  || ','
  ||
  CASE IS_VISIBLE
    WHEN 1
    THEN 'CHECKED_IN'
    ELSE 'NOT_CHECKED_IN'
  END WARN
FROM
  (
  --MAPPING SELECT
  SELECT MAPG.MAPPING_NAME OBJ_NAME,
    'mapping' OBJ_TYPE,
    MAPG.SUBJECT_ID SUBJ_ID,
    1 - (MAPG.VERSION_NUMBER - LABEL.VERSION_NUMBER) LABELLED_LATEST,
    MAPG.IS_VISIBLE
  FROM INFOMETA.OPB_MAPPING MAPG
  INNER JOIN
    (SELECT B.OBJECT_ID,
      B.OBJECT_TYPE,
      B.VERSION_NUMBER,
      B.SUBJECT_ID
    FROM INFOMETA.REP_LABEL A
    INNER JOIN INFOMETA.REP_LABEL_REF B
    ON A.LABEL_ID              = B.LABEL_ID
    WHERE A.LABEL_NAME         = '$crq'
    AND B.OBJECT_TYPE          = 21
    ) LABEL ON LABEL.OBJECT_ID = MAPG.MAPPING_ID
  AND LABEL.SUBJECT_ID         = MAPG.SUBJECT_ID
  INNER JOIN
    (SELECT MAX(IS_VISIBLE) MAX_VISIBLE,
      MAPPING_ID,
      SUBJECT_ID
    FROM INFOMETA.OPB_MAPPING
    GROUP BY MAPPING_ID,
      SUBJECT_ID
    ) VIS
  ON MAPG.MAPPING_ID    = VIS.MAPPING_ID
  AND MAPG.SUBJECT_ID   = VIS.SUBJECT_ID
  WHERE MAPG.IS_VISIBLE = VIS.MAX_VISIBLE
  --END MAPPING SELECT
  UNION
  --TASK/WORKFLOW SELECT
  SELECT TASK.TASK_NAME OBJ_NAME,
    CASE LABEL.OBJECT_TYPE
      WHEN 58
      THEN 'command'
      WHEN 68
      THEN 'session'
      WHEN 70
      THEN 'worklet'
      WHEN 71
      THEN 'workflow'
      ELSE NULL
    END OBJ_TYPE,
    TASK.SUBJECT_ID SUBJ_ID,
    1 - (TASK.VERSION_NUMBER - LABEL.VERSION_NUMBER) LABELLED_LATEST,
    TASK.IS_VISIBLE
  FROM INFOMETA.OPB_TASK TASK
  INNER JOIN
    (SELECT B.OBJECT_ID,
      B.OBJECT_TYPE,
      B.VERSION_NUMBER,
      B.SUBJECT_ID
    FROM INFOMETA.REP_LABEL A
    INNER JOIN INFOMETA.REP_LABEL_REF B
    ON A.LABEL_ID              = B.LABEL_ID
    WHERE A.LABEL_NAME         = '$crq'
    AND B.OBJECT_TYPE         IN (58, 68, 70, 71)
    ) LABEL ON LABEL.OBJECT_ID = TASK.TASK_ID
  AND LABEL.SUBJECT_ID         = TASK.SUBJECT_ID
  INNER JOIN
    (SELECT MAX(IS_VISIBLE) MAX_VISIBLE,
      TASK_ID,
      SUBJECT_ID
    FROM INFOMETA.OPB_TASK
    GROUP BY TASK_ID,
      SUBJECT_ID
    ) VIS
  ON VIS.TASK_ID        = TASK.TASK_ID
  AND VIS.SUBJECT_ID    = TASK.SUBJECT_ID
  WHERE TASK.IS_VISIBLE = VIS.MAX_VISIBLE
  AND TASK.IS_REUSABLE  = 1
  --END TASK/WORKFLOW SELECT
  UNION
  --SOURCE SELECT
  SELECT SRC.SOURCE_NAME OBJ_NAME,
    'source' OBJ_TYPE,
    SRC.SUBJ_ID SUBJ_ID,
    1 - (SRC.VERSION_NUMBER - LABEL.VERSION_NUMBER) LABELLED_LATEST,
    SRC.IS_VISIBLE
  FROM INFOMETA.OPB_SRC SRC
  INNER JOIN
    (SELECT B.OBJECT_ID,
      B.OBJECT_TYPE,
      B.VERSION_NUMBER,
      B.SUBJECT_ID
    FROM INFOMETA.REP_LABEL A
    INNER JOIN INFOMETA.REP_LABEL_REF B
    ON A.LABEL_ID              = B.LABEL_ID
    WHERE A.LABEL_NAME         = '$crq'
    AND B.OBJECT_TYPE          = 1
    ) LABEL ON LABEL.OBJECT_ID = SRC.SRC_ID
  AND LABEL.SUBJECT_ID         = SRC.SUBJ_ID
  INNER JOIN
    (SELECT MAX(IS_VISIBLE) MAX_VISIBLE,
      SRC_ID,
      SUBJ_ID
    FROM INFOMETA.OPB_SRC
    GROUP BY SRC_ID,
      SUBJ_ID
    )VIS
  ON VIS.SRC_ID        = SRC.SRC_ID
  AND VIS.SUBJ_ID      = SRC.SUBJ_ID
  WHERE SRC.IS_VISIBLE = VIS.MAX_VISIBLE
  --END SOURCE SELECT
  UNION
  --TARGET SELECT
  SELECT TARG.TARGET_NAME OBJ_NAME,
    'target' OBJ_TYPE,
    TARG.SUBJ_ID SUBJ_ID,
    1 - (TARG.VERSION_NUMBER - LABEL.VERSION_NUMBER) LABELLED_LATEST,
    TARG.IS_VISIBLE
  FROM INFOMETA.OPB_TARG TARG
  INNER JOIN
    (SELECT B.OBJECT_ID,
      B.OBJECT_TYPE,
      B.VERSION_NUMBER,
      B.SUBJECT_ID
    FROM INFOMETA.REP_LABEL A
    INNER JOIN INFOMETA.REP_LABEL_REF B
    ON A.LABEL_ID              = B.LABEL_ID
    WHERE A.LABEL_NAME         = '$crq'
    AND B.OBJECT_TYPE          = 2
    ) LABEL ON LABEL.OBJECT_ID = TARG.TARGET_ID
  AND LABEL.SUBJECT_ID         = TARG.SUBJ_ID
  INNER JOIN
    (SELECT MAX(IS_VISIBLE) MAX_VISIBLE,
      TARGET_ID,
      SUBJ_ID
    FROM INFOMETA.OPB_TARG
    GROUP BY TARGET_ID,
      SUBJ_ID
    )VIS
  ON VIS.TARGET_ID      = TARG.TARGET_ID
  AND VIS.SUBJ_ID       = TARG.SUBJ_ID
  WHERE TARG.IS_VISIBLE = VIS.MAX_VISIBLE
  --END TARGET SELECT
  UNION
  --TRANSFORMATION SELECT
  SELECT TRANS.WIDGET_NAME OBJ_NAME,
    'transformation' OBJ_TYPE,
    TRANS.SUBJECT_ID SUBJ_ID,
    1 - (TRANS.VERSION_NUMBER - LABEL.VERSION_NUMBER) LABELLED_LATEST,
    TRANS.IS_VISIBLE
  FROM INFOMETA.OPB_WIDGET TRANS
  INNER JOIN
    (SELECT B.OBJECT_ID,
      B.OBJECT_TYPE,
      B.VERSION_NUMBER,
      B.SUBJECT_ID
    FROM INFOMETA.REP_LABEL A
    INNER JOIN INFOMETA.REP_LABEL_REF B
    ON A.LABEL_ID      = B.LABEL_ID
    WHERE A.LABEL_NAME = '$crq'
    AND OBJECT_TYPE BETWEEN 4 AND 16
    ) LABEL ON LABEL.OBJECT_ID = TRANS.WIDGET_ID
  AND LABEL.OBJECT_TYPE        = TRANS.WIDGET_TYPE
  AND LABEL.SUBJECT_ID         = TRANS.SUBJECT_ID
  INNER JOIN
    (SELECT MAX(IS_VISIBLE) MAX_VISIBLE,
      WIDGET_ID,
      SUBJECT_ID
    FROM INFOMETA.OPB_WIDGET
    GROUP BY WIDGET_ID,
      SUBJECT_ID
    ) VIS
  ON VIS.WIDGET_ID       = TRANS.WIDGET_ID
  AND VIS.SUBJECT_ID     = TRANS.SUBJECT_ID
  WHERE TRANS.IS_VISIBLE = VIS.MAX_VISIBLE
  AND TRANS.IS_REUSABLE  = 1
  --END TRANSFORMATION SELECT
  UNION
  --SHORCUT SELECT
  SELECT SHORTCUT.SHORTCUT_NAME OBJ_NAME,
    CASE SHORTCUT.OBJECT_TYPE
      WHEN 23
      THEN 'transformation'
      WHEN 24
      THEN 'target'
      WHEN 25
      THEN 'source'
      ELSE NULL
    END OBJ_TYPE,
    SHORTCUT.SUBJECT_ID SUBJ_ID,
    1 - (SHORTCUT.VERSION_NUMBER - LABEL.VERSION_NUMBER) LABELLED_LATEST,
    SHORTCUT.IS_VISIBLE
  FROM INFOMETA.OPB_SHORTCUT SHORTCUT
  INNER JOIN
    (SELECT B.OBJECT_ID,
      B.OBJECT_TYPE,
      B.VERSION_NUMBER,
      B.SUBJECT_ID
    FROM INFOMETA.REP_LABEL A
    INNER JOIN INFOMETA.REP_LABEL_REF B
    ON A.LABEL_ID              = B.LABEL_ID
    WHERE A.LABEL_NAME         = '$crq'
    AND B.OBJECT_TYPE         IN (23, 24, 25)
    ) LABEL ON LABEL.OBJECT_ID = SHORTCUT.OBJECT_ID
  AND LABEL.OBJECT_TYPE        = SHORTCUT.OBJECT_TYPE
  AND LABEL.SUBJECT_ID         = SHORTCUT.SUBJECT_ID
  INNER JOIN
    (SELECT MAX(IS_VISIBLE) MAX_VISIBLE,
      OBJECT_ID,
      OBJECT_TYPE,
      SUBJECT_ID
    FROM INFOMETA.OPB_SHORTCUT
    GROUP BY OBJECT_ID,
      OBJECT_TYPE,
      SUBJECT_ID
    ) VIS
  ON VIS.OBJECT_ID          = SHORTCUT.OBJECT_ID
  AND VIS.OBJECT_TYPE       = SHORTCUT.OBJECT_TYPE
  AND VIS.SUBJECT_ID        = SHORTCUT.SUBJECT_ID
  WHERE SHORTCUT.IS_VISIBLE = VIS.MAX_VISIBLE
    --END SHORCUT SELECT
  ) DEPLOY
INNER JOIN INFOMETA.OPB_SUBJECT SUBJ
ON DEPLOY.SUBJ_ID = SUBJ.SUBJ_ID
WHERE 
	DEPLOY.LABELLED_LATEST <> 1
	OR
	DEPLOY.IS_VISIBLE <> 1
ORDER BY OBJ