SELECT
	OPB_SUBJECT.SUBJ_NAME || ','
	|| OPB_SRC.SOURCE_NAME || ','
	|| OPB_SRC_FLD.SRC_NAME || ','
	|| REP_SRC_KEY_TYPES.KEYTYPE_NAME || ','
	|| REP_FLD_DATATYPE.DTYPE_NAME || ','
	|| OPB_PICDSC.SRC_PREC || ','
	|| OPB_PICDSC.SRC_SCALE AS RES
FROM
	infometa.OPB_SRC,
	infometa.OPB_SRC_FLD,
	infometa.OPB_PICDSC,
	infometa.OPB_SUBJECT,
	infometa.REP_SRC_KEY_TYPES,
	infometa.OPB_DBD,
	infometa.OPB_MMD_DBTYPE,
	infometa.REP_FLD_DATATYPE
WHERE
	OPB_SUBJECT.SUBJ_ID      = OPB_SRC.SUBJ_ID
AND OPB_SRC.SUBJ_ID        = OPB_DBD.SUBJ_ID
AND OPB_SRC.SRC_ID         = OPB_SRC_FLD.SRC_ID
AND OPB_SRC_FLD.PICID      = OPB_PICDSC.PICID
AND OPB_SRC_FLD.KEYTYPE    = REP_SRC_KEY_TYPES.KEYTYPE_NUM
AND OPB_SRC.DBDID          = OPB_DBD.DBDID
AND OPB_DBD.DBTYPE         = OPB_MMD_DBTYPE.DBTYPE_ID
AND OPB_PICDSC.SRC_NTYPE   = REP_FLD_DATATYPE.DTYPE_NUM
AND OPB_SRC_FLD.IS_HIDDEN  = 0
AND OPB_SRC.VERSION_NUMBER = OPB_DBD.VERSION_NUMBER
AND OPB_SRC.VERSION_NUMBER = OPB_SRC_FLD.VERSION_NUMBER
AND OPB_SRC.VERSION_NUMBER = OPB_PICDSC.VERSION_NUMBER
AND OPB_SRC.VERSION_NUMBER = OPB_SRC_FLD.VERSION_NUMBER
AND OPB_SRC.IS_VISIBLE     = 1
AND OPB_SUBJECT.SUBJ_NAME	|| '.' || OPB_SRC.SOURCE_NAME 
  IN ($src_list) 
ORDER BY
	OPB_SUBJECT.SUBJ_NAME || ','
	|| OPB_SRC.SOURCE_NAME || ','
	|| OPB_SRC_FLD.SRC_NAME || ','
	|| KEYTYPE_NAME || ','
	|| REP_FLD_DATATYPE.DTYPE_NAME || ','
	|| OPB_PICDSC.SRC_PREC || ','
	|| OPB_PICDSC.SRC_SCALE
  